### ISSUE TITLE
Update posts using /posts endpoint

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#100]
_FEATURE OVERVIEW_
-------------------
#### User Story

The `/posts` endpoint in rogue doesn't update posts, it only creates them. The posts endpoint should both update the post content (like the caption) as well as update stuff like `why_participated` and `quantity` on the signup record. Additionally we should log changes in the `events` table, similar to how we were using the `reportback_logs` table.

**Comment by chloealee** [comment]
@sbsmith86 right now, since we don't allow users to update the captions on reportback items, should we hold off on building the functionality to update the post content?

**Comment by sbsmith86** [comment]
@chloealee I think we can store it, even if we don't ever send it in a request.

**Comment by chloealee** [comment]
@sbsmith86 do you mean build this out even if we don't use it yet?

**Comment by sbsmith86** [comment]
@chloealee yea like, when the request comes in, we can check if `caption` is included and store it on the `photo` record pretty easily. Whether or not we actually send over updated captions, I don't think that matters

**Comment by chloealee** [comment]
@sbsmith86 ah gotcha - will do!

**Comment by chloealee** [comment]
@sbsmith86 thinking through this more, I think there are a lot of unknowns right now about what editing a caption would look like. Right now, the caption is always sent in the request unless it is only changing the reportback (`caption` is `NULL in this case). 

We can do the check to see if a `caption` is included but this could be if the reportback's `quantity` and/or` why_participated` are changed, not neccessarily the reportback item's caption. 

Also, we'd have to pass the reportback item's ID to Rogue to look up and change the specific `photo`'s `caption`. Even in this case, since it's difficult to see if a caption has changed (versus something like `quantity` like we chatted about IRL yesterday), it would always be an update right now, even if the caption isn't changed. 

Since we don't have this functionality right now and in interest of scope, would it be okay to leave this work out of the issue and create a separate issue for this in the future?

**Comment by sbsmith86** [comment]
@chloealee Totally ok to not do this work if it is to complicated at the moment. I didn't delve enough into it!

**Comment by chloealee** [comment]
@sbsmith86 ok cool, thanks! I will make a new separate issue for it so it doesn't get lost in the future!
