### ISSUE TITLE
Update relationship between Posts and Reactions

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#166]
define a one-to-many relationship between the `Post` model and the `Reaction` model. So we can say that a `Post` has many `Reaction`s

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to update the relationships between Posts and Reactions so that it's more clear and follows the new agreed upon model](https://trello.com/c/l3SBa0T8/329-as-a-developer-i-want-to-update-the-relationships-between-posts-and-reactions-so-that-it-s-more-clear-and-follows-the-new-agreed)
