### ISSUE TITLE
Update the Events table and it's relationship with other models

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#167]
Define a polymorphic relationship between and `Event` and the other models Rogue.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to update the relationships between Events and other tables so that it's more clear and follows the new agreed upon model.](https://trello.com/c/XkZNKubY/330-as-a-developer-i-want-to-update-the-relationships-between-events-and-other-tables-so-that-it-s-more-clear-and-follows-the-new-ag)
