### ISSUE TITLE
Update Posts table

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#168]
Update the posts table so more general columns like `status`, `source`, `remote_addr` are stored on the post instead of the `photos` table.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer,  I want to update the Posts table so that it matches what we decided in the model meeting we had](https://trello.com/c/zwRTOpME/331-as-a-developer-i-want-to-update-the-posts-table-so-that-it-matches-what-we-decided-in-the-model-meeting-we-had)
