### ISSUE TITLE
Review quantity_pending logic

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#177]
When you send a request over to the `/posts` endpoint to update quantity you have to send a `quantity_pending` param for the pending quantity to be stored. 

The logic should be that the client sends over a `quantity` param on creation/update and that gets stored in `quantity_pending` until approval. 

Would be open to discussing this further and reviewing it's necessity/how it should work.

**Comment by sbsmith86** [comment]
After talking about this with the team. It sounds like for now we are going to be just using the `quantity` column. We should review the logic/tests and make sure this is working as expected.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to review the `quantity_pending` logic so that we can make sure everythings ok when we stop using it](https://trello.com/c/ysHUJKs5/373-as-a-developer-i-want-to-review-the-quantity-pending-logic-so-that-we-can-make-sure-everythings-ok-when-we-stop-using-it)
