### ISSUE TITLE
/signup validation

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#178]
_FEATURE OVERVIEW_
-------------------
#### User Story

When requests are sent to the `/signup` endpoint we should perform some validation on the request to make sure required fields are present and correctly formatted before trying to store the signup

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🔪 As a developer, I want to add validation to the /signup endpoint so that it gets all the right info 🔪](https://trello.com/c/meT82Tpr/420-as-a-developer-i-want-to-add-validation-to-the-signup-endpoint-so-that-it-gets-all-the-right-info)
