### ISSUE TITLE
Campaign Overview Tests

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#228]
_FEATURE OVERVIEW_
-------------------
#### User Story

Add some unit tests for the `CampaignService` class so we can make sure this is working correctly 
 
#### Why This Matters

I think unit tests make the most sense for this since we are introducing some custom queries to generate the page. This will help us confirm that the work powering the overview page is working correctly.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [As a developer, I want to make some unit tests for the Campaign Overview page because there are some custom queries being used to generate the page.](https://trello.com/c/Zu5MbBbW/372-as-a-developer-i-want-to-make-some-unit-tests-for-the-campaign-overview-page-because-there-are-some-custom-queries-being-used-to)
