### ISSUE TITLE
Remove file_id from reportback_items table

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#33]
We do not need to store this drupal `fid` anymore because rogue does it's own file storage and phoenix will be able to send requests to rogue that target items based on their `id` in the `reportback_items` table.

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;MVGeNWjp&#x2F;4-as-a-developer-i-want-to-remove-file-id-from-reportback-items-table-because-it-s-unused"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As a developer, I want to remove file_id from reportback_items table because it&#39;s unused.</a>

**Comment by chloealee** [comment]
@sbsmith86 if we remove `file_id` from `reportback_items` table, does the below sound correct? 

- `file_id` also gets removed from the `reactions` table and instead of `file_id`, we refer to the reportback item the reaction belongs to by the reportback item's `fid` 
- transformer no longer returns `file_id` for reportback items 
- the reportback a reportback item belongs to is referenced by the reportback item's `id` instead of `file_id`
- naming convention in S3 (this can always be changed in the future too!) is now based on reportback item Rogue `id` instead of the `file_id`

**Comment by sbsmith86** [comment]
Yes! That all sounds correct to me. Except:

> we refer to the reportback item the reaction belongs to by the reportback item's `id` (not `fid`) in the `reportback-items` table.

**Comment by chloealee** [comment]
ok great, thank you! Oh sorry - for that I meant we refer to the report back item the reaction belongs to by the reportback item's `id`, not `fid`?

**Comment by sbsmith86** [comment]
yep!

**Comment by chloealee** [comment]
cool, thank you! Always so helpful to get a quick 👍  to make sure I don't go down the wrong path :)

**Comment by chloealee** [comment]
sorry one more thing, @sbsmith86 ! Do we even need to know about which reportback item the reaction is associated with? Because reactions are on _reportbacks_, not reportback items, right? So in other words, we can just delete `file_id` from the `reactions` table but don't necessarily need to replace that with the `id` of the reportback item?

**Comment by sbsmith86** [comment]
It looks like reactions are currently stored by item: 

![image](https://cloud.githubusercontent.com/assets/1700409/18525947/aa375886-7a8c-11e6-8e11-4e36ed21a186.png)

So in rogue that would mean instead of storing `fid` we would store reportback-item `id`

**Comment by chloealee** [comment]
so does this mean we have the models incorrect in Rogue? So we should also change the below?

- Reactions belong to many ReportbackItems instead of Reportbacks
- ReportbackItems belong to many Reactions instead of Reportbacks belong to many Reactions
- Pivot table should be `reaction_reportbackitems` instead of `reaction_reportback`

**Comment by sbsmith86** [comment]
@chloealee that sounds right to me

**Comment by chloealee** [comment]
awesome, thanks @sbsmith86 !

**Comment by ngjo** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;DHRsTNt3&#x2F;34-as-an-impact-team-member-i-would-like-to-be-able-to-schedule-message-sends-so-that-i-don-t-have-to-do-them-over-the-weekend-or-o"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> As an impact team member, I would like to be able to schedule message sends so that I don&#39;t have to do them over the weekend or on off days.</a>
