### ISSUE TITLE
Tag structure

### ISSUE THREAD

**Issue by katiecrane** [DoSomething/rogue#353]
_Thinkin' 'bout taggin'_
-------------------
#### Current Behavior
Right now, we are using [rtconner/laravel-tagging](https://github.com/rtconner/laravel-tagging).

#### Desired Behavior
We'd like to calm things down a bit. Perhaps using a regular ol' `hasMany` relationship.

#### Steps to Replicate
Hit this endpoint `api/v1/reportbacks`. Screenshots below are from this endpoint.

#### Why This Matters
We are running into issues where this makes some yucky sequel queries. 

For example, this is to not include posts tagged as `Hide In Gallery` in the overall results.

![image](https://user-images.githubusercontent.com/4240292/29184977-e2980f84-7dd5-11e7-90f2-d3dd01890359.png)

And this looks like it pulls the details of the tag for each post?

![image](https://user-images.githubusercontent.com/4240292/29185046-16b1751c-7dd6-11e7-84e1-d8100018569a.png)

**Comment by katiecrane** [comment]
I played around locally with using a plain ol' pivot table. I tagged all the posts I have locally except one as "Hide In Gallery" and this is what runs when you hit the same endpoint as above:

![image](https://user-images.githubusercontent.com/4240292/29279756-e0832206-80e6-11e7-8182-3b1586b2e204.png)

The good news is that the big nasty query is gone!

**Comment by katiecrane** [comment]
Update: this query will only ever have 20 post ids because of the pagination, so I don't think we need to worry about it.

![image](https://user-images.githubusercontent.com/4240292/29286945-d2048bf0-8101-11e7-8611-7414090c5593.png)

**Comment by ngjo** [comment]
**Meeting Recap**
We met as a team and it sounds like we're all on board to move away from the tagging package and do our own thing. 

The reason we went with the package in the first place was because we (1) weren't sure what the tags would be (2) it did offer some good solutions at the time for tagging and (3) we were moving quickly to launch. Now, once we've had a chance to see how the tags system works and how we want it to work as we continue to develop new features, the package doesn't necessarily serve us well anymore.

Briefly, here are the next steps that we've broken down into cards and will be tackled during the 8/14 sprint:

1. Make new tables and relationships
2.  Update code that references old tag stuff w/ empty placeholders so the code doesn't error out + (killconner)
3. Go back to empty placeholders and fix it as you would expect it to to work and write unit tests
4. Update posts tags endpoint to work with the new tags 
5. Rerun tag script on Phoenix-thor and make any changes necessary
6. Rethinking: As a developer, I want to update the rogue RB endpoint so that it's prioritizing posts that are tagged as Good Photo first and hiding 'Excluded' tagged RBs

Follow along here (tags refactoring label) on Pivotal: https://www.pivotaltracker.com/n/projects/2019429/search?q=label%3A%22tag%20refactoring%22
