### ISSUE TITLE
Pull in user information into rogue using Northstar or Cached data

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#71]
_FEATURE OVERVIEW_
-------------------
#### User Story

Eventually we will want to be able to expose important user information in rogue. To do this we should implement a system in rogue that when wanting to display user information will first look in Cache and grab the user info from there. If it isn't found there, make the call to Northstar to grab the user info and also store that information in cache so that the next time we need that users information it will be there (or not be there depending on when we expire the cache.)

#### Why This Matters

When we start to build out the admin interface for Rogue we will want to be able to display things like user name, email, address, etc.

**Comment by ngjo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(18) As a developer, I want to create functionality that grabs user info from northstar (i.e. we store info cache) so that I can grab reportback info. (2 of 3)](https://trello.com/c/imxFwZMM/106-18-as-a-developer-i-want-to-create-functionality-that-grabs-user-info-from-northstar-i-e-we-store-info-cache-so-that-i-can-grab-)
