### ISSUE TITLE
Authentication via Northstar

### ISSUE THREAD

**Issue by sbsmith86** [DoSomething/rogue#9]
Allow admins to authenticate via Northstar. 

[See example](https://github.com/DoSomething/gladiator/pull/12) of how we did this in gladiator 

Or is there a better way of doing this now, with the `Northstar-php` package? @DFurnes @weerd

**Comment by weerd** [comment]
Yeah, don't use the example in Gladiator. Best to use the [Northstar-PHP](https://github.com/DoSomething/northstar-php) package.

**Comment by DFurnes** [comment]
Yeah, I'd recommend following Aurora's example for this and using Northstar-PHP. One minor warning: I haven't tested it with Laravel 5.2 yet (Aurora is still on 5.1) so you might run into some little gotchas there. Let me know if I can help at all! 😄

**Comment by chloealee** [comment]
hey @DFurnes ! Working on setting up rogue authentication via Northstar. I followed all the instructions [here](https://github.com/DoSomething/northstar-php) already. When you said to follow Aurora's example, do you mean to add something like [this file](https://github.com/DoSomething/northstar-php/blob/master/src/Northstar.php) to Rogue? I tried to look through Aurora's code base to see any updates that use Northstar-PHP but wasn't able to find anything so confused as to how it uses Northstar-PHP?

**Comment by DFurnes** [comment]
The `Northstar` class that you linked is part of the package, so it can be included via Composer rather than by copying-and-pasting the file into the application's source code. Aurora uses that class fairly extensively (ex: [1](https://github.com/DoSomething/aurora/blob/793f630cb0cc31d31bd36c35e2a7859260568e13/app/Http/Controllers/UsersController.php#L14-L22), [2](https://github.com/DoSomething/aurora/blob/master/app/Http/Controllers/ClientController.php#L12-L20)) - it's how it reads and updates user & client data from Northstar!

Once you've included the Northstar PHP class and followed the instructions in the readme to configure it, you can also [use the included `northstar` authentication driver](https://github.com/DoSomething/northstar-php#laravel-authentication) so that the default Laravel authentication methods will query against Northstar rather than the local database.

**Comment by chloealee** [comment]
ah got it, thanks for explaining in more details @DFurnes ! I've already included the `northstar` authentication driver - is that all that is needed to allow admins to authenticate via Northstar? Doesn't seem like (for now) we need to read or update user data from Northstar like Aurora does and only needs to authenticate?

**Comment by DFurnes** [comment]
Oh, then that's pretty much it! You'll probably want to have a [role middleware](https://github.com/DoSomething/aurora/blob/793f630cb0cc31d31bd36c35e2a7859260568e13/app/Http/Middleware/CheckRole.php) like Aurora so that only users with the admin role can do things on Rogue as well.

**Comment by chloealee** [comment]
ah got it - Northstar-PHP is so nice! I was overthinking it but now understand - thanks Dave! Will add the role middleware now :)

**Comment by sbsmith86** [comment]
@chloealee can we close this?

**Comment by chloealee** [comment]
@sbsmith86 almost done with this! I just am testing to make sure that it is hooked up correctly and am seeing some strange errors. I'll merge when I figure it out/Dave has one last look!
